/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Opt(IDL.Text),
});
export const Event = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const Sermon = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'scriptureReference' : IDL.Text,
  'speaker' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'listSermons' : IDL.Func([], [IDL.Vec(Sermon)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Opt(IDL.Text),
  });
  const Event = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const Sermon = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'scriptureReference' : IDL.Text,
    'speaker' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'listSermons' : IDL.Func([], [IDL.Vec(Sermon)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };